name: build and deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # 环境镜像

    permissions:
      contents: read
      pages: write
      id-token: write

    concurrency:
      group: 'pages'
      cancel-in-progress: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          version: 16

      - name: Install dependencies
        run: npm install

      - name: Run Vite build
        run: npm run build-only

      - name: Stop Vite server
        run: |
          kill $(lsof -t -i:5173)  # 停止端口为 5173 的进程

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
